// FrontEndReact_V1.1/frontend-app/src/shared/ui/components/ConfirmModal.tsx
import { type ReactNode } from 'react';
import { Button, Modal, Spinner } from 'react-bootstrap';

export type ConfirmVariant = 'primary' | 'danger' | 'warning' | 'success' | 'info';

interface ConfirmModalProps {
  show: boolean;
  title: string;
  message: ReactNode;
  confirmLabel?: string;
  cancelLabel?: string;
  confirmVariant?: ConfirmVariant;
  confirmIcon?: string;
  loadingLabel?: string;
  loading?: boolean;
  size?: 'sm' | 'lg' | 'xl';
  onConfirm: () => void | Promise<void>;
  onHide: () => void;
}

export function ConfirmModal({
  show,
  title,
  message,
  confirmLabel = 'Confirmar',
  cancelLabel = 'Cancelar',
  confirmVariant = 'danger',
  confirmIcon = 'bi-check-circle',
  loadingLabel = 'Procesando…',
  loading = false,
  size,
  onConfirm,
  onHide,
}: ConfirmModalProps) {
  const handleConfirm = async () => {
    if (loading) return;
    await onConfirm();
  };

  const handleHide = () => {
    if (loading) return;
    onHide();
  };

  return (
    <Modal
      show={show}
      onHide={handleHide}
      centered
      size={size}
      backdrop={loading ? 'static' : true}
      keyboard={!loading}
    >
      <Modal.Header closeButton={!loading}>
        <Modal.Title>{title}</Modal.Title>
      </Modal.Header>
      <Modal.Body>{message}</Modal.Body>
      <Modal.Footer>
        <Button variant="outline-secondary" onClick={handleHide} disabled={loading}>
          <i className="bi bi-x-circle me-1" />
          {cancelLabel}
        </Button>
        <Button variant={confirmVariant} onClick={handleConfirm} disabled={loading}>
          {loading ? (
            <>
              <Spinner animation="border" size="sm" className="me-1" />
              {loadingLabel}
            </>
          ) : (
            <>
              <i className={`bi ${confirmIcon} me-1`} />
              {confirmLabel}
            </>
          )}
        </Button>
      </Modal.Footer>
    </Modal>
  );
}

// FrontEndAngular_V1.1/frontend-app/src/shared/ui/components/confirm-modal.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { ModalComponent } from './modal.component';

export type ConfirmVariant = 'primary' | 'danger' | 'warning' | 'success' | 'info';

/**
 * Modal de confirmación (equivalente a `ConfirmModal`). El mensaje se pasa con
 * `message` (texto) o proyectando contenido: <app-confirm-modal>…</app-confirm-modal>.
 */
@Component({
  selector: 'app-confirm-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ModalComponent],
  template: `
    <app-modal
      [show]="show()"
      [centered]="true"
      [size]="size()"
      [backdrop]="loading() ? 'static' : true"
      [keyboard]="!loading()"
      (hide)="handleHide()"
    >
      <div class="modal-header">
        <div class="modal-title h4">{{ title() }}</div>
        @if (!loading()) {
          <button type="button" class="btn-close" aria-label="Close" (click)="handleHide()"></button>
        }
      </div>
      <div class="modal-body">
        @if (message()) {
          {{ message() }}
        }
        <ng-content />
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" (click)="handleHide()" [disabled]="loading()">
          <i class="bi bi-x-circle me-1"></i>
          {{ cancelLabel() }}
        </button>
        <button type="button" class="btn" [class]="'btn-' + confirmVariant()" (click)="handleConfirm()" [disabled]="loading()">
          @if (loading()) {
            <span class="spinner-border spinner-border-sm me-1" role="status"></span>
            {{ loadingLabel() }}
          } @else {
            <i class="bi me-1" [class]="confirmIcon()"></i>
            {{ confirmLabel() }}
          }
        </button>
      </div>
    </app-modal>
  `,
})
export class ConfirmModalComponent {
  readonly show = input<boolean>(false);
  readonly title = input.required<string>();
  readonly message = input<string | null>(null);
  readonly confirmLabel = input<string>('Confirmar');
  readonly cancelLabel = input<string>('Cancelar');
  readonly confirmVariant = input<ConfirmVariant>('danger');
  readonly confirmIcon = input<string>('bi-check-circle');
  readonly loadingLabel = input<string>('Procesando…');
  readonly loading = input<boolean>(false);
  readonly size = input<'sm' | 'lg' | 'xl' | undefined>(undefined);

  readonly confirm = output<void>();
  readonly hide = output<void>();

  protected handleConfirm(): void {
    if (this.loading()) return;
    this.confirm.emit();
  }

  protected handleHide(): void {
    if (this.loading()) return;
    this.hide.emit();
  }
}
