// FrontEndReact_V1.1/sufiatulado-app/src/shared/ui/components/EmptyState.tsx
interface Props {
  icon?: string;
  title: string;
  description?: string;
  action?: React.ReactNode;
}

export function EmptyState({ icon = 'bi-inbox', title, description, action }: Props) {
  return (
    <div className="text-center py-5 px-4">
      <i className={`bi ${icon}`} style={{ fontSize: '3rem', color: '#B2BFCC' }} />
      <h6 className="mt-3 fw-semibold" style={{ color: '#333241' }}>{title}</h6>
      {description && <p className="text-muted small mb-3">{description}</p>}
      {action}
    </div>
  );
}

// FrontEndAngular_V1.1/frontend-app/src/shared/ui/components/empty-state.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

/** Estado vacío. La acción opcional se proyecta como contenido. */
@Component({
  selector: 'app-empty-state',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="text-center py-5 px-4">
      <i class="bi" [class]="icon()" style="font-size: 3rem; color: #B2BFCC"></i>
      <h6 class="mt-3 fw-semibold" style="color: #333241">{{ title() }}</h6>
      @if (description()) {
        <p class="text-muted small mb-3">{{ description() }}</p>
      }
      <ng-content />
    </div>
  `,
})
export class EmptyStateComponent {
  readonly icon = input<string>('bi-inbox');
  readonly title = input.required<string>();
  readonly description = input<string | undefined>(undefined);
}
