// FrontEndReact_V1.1/sufiatulado-app/src/shared/ui/components/ErrorBoundaryFallback.tsx
interface Props {
  error?: Error;
  resetErrorBoundary?: () => void;
}

export function ErrorBoundaryFallback({ error, resetErrorBoundary }: Props) {
  return (
    <div className="d-flex flex-column align-items-center justify-content-center py-5 px-4 text-center">
      <i className="bi bi-exclamation-triangle-fill text-warning" style={{ fontSize: '3rem' }} />
      <h5 className="mt-3 fw-bold">Ocurrió un error</h5>
      <p className="text-muted small mb-3">{error?.message ?? 'Error inesperado'}</p>
      {resetErrorBoundary && (
        <button className="btn btn-outline-primary btn-sm" onClick={resetErrorBoundary}>
          <i className="bi bi-arrow-clockwise me-1" />
          Reintentar
        </button>
      )}
    </div>
  );
}

// FrontEndAngular_V1.1/frontend-app/src/shared/ui/components/error-boundary-fallback.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';

@Component({
  selector: 'app-error-boundary-fallback',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="d-flex flex-column align-items-center justify-content-center py-5 px-4 text-center">
      <i class="bi bi-exclamation-triangle-fill text-warning" style="font-size: 3rem"></i>
      <h5 class="mt-3 fw-bold">Ocurrió un error</h5>
      <p class="text-muted small mb-3">{{ error()?.message ?? 'Error inesperado' }}</p>
      @if (resettable()) {
        <button class="btn btn-outline-primary btn-sm" (click)="reset.emit()">
          <i class="bi bi-arrow-clockwise me-1"></i>
          Reintentar
        </button>
      }
    </div>
  `,
})
export class ErrorBoundaryFallbackComponent {
  readonly error = input<Error | undefined>(undefined);
  readonly resettable = input<boolean>(false);
  readonly reset = output<void>();
}
