// FrontEndReact_V1.1/sufiatulado-app/src/shared/ui/components/LoadingSpinner.tsx
interface Props {
  fullPage?: boolean;
  text?: string;
}

export function LoadingSpinner({ fullPage = false, text = 'Cargando...' }: Props) {
  if (fullPage) {
    return (
      <div
        className="d-flex flex-column align-items-center justify-content-center"
        style={{ minHeight: '60vh' }}
        role="status"
        aria-label={text}
      >
        <div
          className="spinner-border mb-3"
          style={{ width: '2.5rem', height: '2.5rem', color: '#FF0026' }}
        />
        <p className="text-muted small mb-0">{text}</p>
      </div>
    );
  }
  return (
    <span className="spinner-border spinner-border-sm" role="status" aria-label={text} />
  );
}

// FrontEndAngular_V1.1/frontend-app/src/shared/ui/components/loading-spinner.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'app-loading-spinner',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (fullPage()) {
      <div
        class="d-flex flex-column align-items-center justify-content-center"
        style="min-height: 60vh"
        role="status"
        [attr.aria-label]="text()"
      >
        <div class="spinner-border mb-3" style="width: 2.5rem; height: 2.5rem; color: #FF0026"></div>
        <p class="text-muted small mb-0">{{ text() }}</p>
      </div>
    } @else {
      <span class="spinner-border spinner-border-sm" role="status" [attr.aria-label]="text()"></span>
    }
  `,
})
export class LoadingSpinnerComponent {
  readonly fullPage = input<boolean>(false);
  readonly text = input<string>('Cargando...');
}
