// FrontEndAngular_V1.1/frontend-app/src/shared/ui/idle-warning-modal.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { ModalComponent } from './components/modal.component';

@Component({
  selector: 'app-idle-warning-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ModalComponent],
  template: `
    <app-modal [show]="show()" backdrop="static" [centered]="true" (hide)="cerrar.emit()">
      <div class="modal-header">
        <div class="modal-title h4">Tu sesion esta por expirar</div>
      </div>
      <div class="modal-body">
        Por seguridad (AP-0129), tu sesion se cerrara por inactividad en
        <strong>{{ segundosRestantes() }}</strong> segundos. Deseas continuar conectado?
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-outline-secondary" (click)="cerrar.emit()">
          Cerrar sesion
        </button>
        <button type="button" class="btn btn-primary" (click)="continuar.emit()">
          Continuar conectado
        </button>
      </div>
    </app-modal>
  `,
})
export class IdleWarningModalComponent {
  readonly show = input<boolean>(false);
  readonly segundosRestantes = input<number>(60);
  readonly continuar = output<void>();
  readonly cerrar = output<void>();
}

// FrontEndReact_V1.1/frontend-app/src/shared/ui/IdleWarningModal.tsx
import { Button, Modal } from 'react-bootstrap';

export interface IdleWarningModalProps {
  show: boolean;
  segundosRestantes: number;
  onContinuar: () => void;
  onCerrar: () => void;
}

export function IdleWarningModal({
  show,
  segundosRestantes,
  onContinuar,
  onCerrar,
}: IdleWarningModalProps): JSX.Element {
  return (
    <Modal show={show} onHide={onCerrar} backdrop="static" centered>
      <Modal.Header>
        <Modal.Title>Tu sesion esta por expirar</Modal.Title>
      </Modal.Header>
      <Modal.Body>
        Por seguridad (AP-0129), tu sesion se cerrara por inactividad en{' '}
        <strong>{segundosRestantes}</strong> segundos. Deseas continuar conectado?
      </Modal.Body>
      <Modal.Footer>
        <Button variant="outline-secondary" onClick={onCerrar}>
          Cerrar sesion
        </Button>
        <Button variant="primary" onClick={onContinuar}>
          Continuar conectado
        </Button>
      </Modal.Footer>
    </Modal>
  );
}
