// FrontEndAngular_V1.1/sufiatulado-app/src/pages/reportes/reportes-page.component.ts
import { ChangeDetectionStrategy, Component, computed, effect, inject, signal } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { ApiClient } from '../../shared/api/client';
import { PageHeaderComponent } from '../../shared/ui/components/page-header.component';
import { PROGRAMA, QUERY_KEYS } from '../../shared/config/constants';
import { injectGenerarReporte, injectObtenerPreviewReporte } from '../../features/reportes/model/queries';
import { REPORTE_TIPO, type ReporteParams, type ReporteTipo } from '../../features/reportes/model/types';
import type { Subprograma } from '../../shared/api/catalogos';

interface FormState {
  tipo: ReporteTipo;
  programa: number;
  subprograma: number | '';
  fecha_inicio: string;
  fecha_fin: string;
  cedula: string;
  estado: number | '';
}

const TIPOS_REPORTE: ReadonlyArray<{ value: ReporteTipo; label: string }> = [
  { value: REPORTE_TIPO.HOJA_VIDA, label: 'Hoja de vida' },
  { value: REPORTE_TIPO.INFO_LABORAL, label: 'Información laboral' },
  { value: REPORTE_TIPO.PLANTILLA_PARTICIPANTES, label: 'Plantilla participantes' },
  { value: REPORTE_TIPO.INFO_TRIBUTARIA, label: 'Información tributaria' },
  { value: REPORTE_TIPO.USUARIOS_MIGRADOS, label: 'Usuarios migrados' },
  { value: REPORTE_TIPO.DEFAULT, label: 'Listado básico' },
  { value: REPORTE_TIPO.ESTADOS_PERFILES, label: 'Estados de perfiles' },
];

const ESTADOS_PERFIL: ReadonlyArray<{ value: number; label: string }> = [
  { value: 3, label: 'Todos' },
  { value: 0, label: 'Incompleto' },
  { value: 1, label: 'Completo' },
  { value: 2, label: 'Pendiente por documentación' },
];

const PAGE_SIZE_OPTIONS: ReadonlyArray<number> = [10, 20, 30];

const TIPOS_SIN_PROGRAMA: readonly ReporteTipo[] = [
  REPORTE_TIPO.INFO_LABORAL,
  REPORTE_TIPO.INFO_TRIBUTARIA,
  REPORTE_TIPO.USUARIOS_MIGRADOS,
];

function renderCell(value: string | number | boolean | null): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'Sí' : 'No';
  return String(value);
}

@Component({
  selector: 'app-reportes-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PageHeaderComponent],
  template: `
    <div>
      <app-page-header
        title="Reportes"
        subtitle="Genera vista previa o descarga en Excel"
        icon="bi-file-earmark-bar-graph"
      />

      <!-- Configurar reporte -->
      <div class="card shadow-sm mb-3" style="border: none">
        <div class="card-body p-4">
          <form (submit)="handleGenerarExcel($event)">
            <h6 class="fw-bold mb-3 text-sufi-navy">Configurar reporte</h6>

            @if (generar.isError()) {
              <div class="alert alert-danger py-2">
                <i class="bi bi-exclamation-circle me-2"></i>
                Error al generar el reporte. Verifica los filtros e intenta de nuevo.
              </div>
            }
            @if (generar.isSuccess()) {
              <div class="alert alert-success py-2">
                <i class="bi bi-check-circle me-2"></i>
                Reporte generado y descargado correctamente.
              </div>
            }
            @if (preview.isError()) {
              <div class="alert alert-danger py-2">
                <i class="bi bi-exclamation-circle me-2"></i>
                Error al obtener la vista previa. Verifica los filtros e intenta de nuevo.
              </div>
            }

            <div class="row g-3">
              <div class="col-md-6">
                <label class="form-label" for="rep-tipo">Tipo de reporte</label>
                <select id="rep-tipo" class="form-select" (change)="setTipo($any($event.target).value)">
                  @for (t of tiposReporte; track t.value) {
                    <option [value]="t.value" [selected]="t.value === params().tipo">{{ t.label }}</option>
                  }
                </select>
              </div>

              @if (!ocultarPrograma()) {
                <div class="col-md-6">
                  <label class="form-label" for="rep-programa">Programa</label>
                  <select id="rep-programa" class="form-select" (change)="setPrograma($any($event.target).value)">
                    <option [value]="programaMovilidad" [selected]="params().programa === programaMovilidad">
                      Movilidad (Vehículos)
                    </option>
                    <option [value]="programaConsumo" [selected]="params().programa === programaConsumo">
                      Consumo y Servicios
                    </option>
                  </select>
                </div>

                <div class="col-md-6">
                  <label class="form-label" for="rep-subprograma">Subprograma</label>
                  <select
                    id="rep-subprograma"
                    class="form-select"
                    [disabled]="subprogramaDisabled()"
                    (change)="setSubprograma($any($event.target).value)"
                  >
                    <option value="" [selected]="params().subprograma === ''">Todos</option>
                    @for (sub of subprogramasQuery.data() ?? []; track sub.cspid) {
                      <option [value]="sub.cspid" [selected]="sub.cspid === params().subprograma">
                        {{ sub.cspid_nombre }}
                      </option>
                    }
                  </select>
                </div>
              }

              <div class="col-12 col-md-6">
                <div class="row g-2">
                  <div class="col-12 col-md-6">
                    <label class="form-label" for="rep-fi">
                      Fecha inicio
                      @if (fechasObligatorias) {
                        <span class="text-danger ms-1">*</span>
                      }
                    </label>
                    <input
                      id="rep-fi"
                      type="date"
                      class="form-control"
                      [value]="params().fecha_inicio"
                      [attr.max]="params().fecha_fin || null"
                      [required]="fechasObligatorias"
                      (input)="patch({ fecha_inicio: $any($event.target).value })"
                    />
                  </div>
                  <div class="col-12 col-md-6">
                    <label class="form-label" for="rep-ff">
                      Fecha fin
                      @if (fechasObligatorias) {
                        <span class="text-danger ms-1">*</span>
                      }
                    </label>
                    <input
                      id="rep-ff"
                      type="date"
                      class="form-control"
                      [value]="params().fecha_fin"
                      [attr.min]="params().fecha_inicio || null"
                      [required]="fechasObligatorias"
                      (input)="patch({ fecha_fin: $any($event.target).value })"
                    />
                  </div>
                </div>
              </div>
              @if (errorFechas()) {
                <div class="col-12">
                  <div class="alert alert-warning py-2 mb-0">
                    <i class="bi bi-exclamation-triangle me-2"></i>{{ errorFechas() }}
                  </div>
                </div>
              }

              @if (mostrarEstadoYCedula()) {
                <div class="col-md-6">
                  <label class="form-label" for="rep-cedula">Cédula</label>
                  <input
                    id="rep-cedula"
                    type="text"
                    class="form-control"
                    placeholder="Solo dígitos"
                    [value]="params().cedula"
                    (input)="onCedula($event)"
                  />
                </div>
                <div class="col-md-6">
                  <label class="form-label" for="rep-estado">Estado</label>
                  <select id="rep-estado" class="form-select" (change)="setEstado($any($event.target).value)">
                    <option value="" [selected]="params().estado === ''">Todos</option>
                    @for (estado of estadosFiltrables; track estado.value) {
                      <option [value]="estado.value" [selected]="estado.value === params().estado">
                        {{ estado.label }}
                      </option>
                    }
                  </select>
                </div>
              }
            </div>

            <div class="mt-4 d-flex flex-wrap gap-2">
              <button type="button" class="btn btn-primary" (click)="handleGenerarPreview()" [disabled]="preview.isPending()">
                @if (preview.isPending()) {
                  <span class="spinner-border spinner-border-sm me-2"></span>Generando…
                } @else {
                  <i class="bi bi-eye me-2"></i>Generar
                }
              </button>
              <button type="submit" class="btn btn-success" [disabled]="generar.isPending()">
                @if (generar.isPending()) {
                  <span class="spinner-border spinner-border-sm me-2"></span>Descargando…
                } @else {
                  <i class="bi bi-file-earmark-excel me-2"></i>Descargar Excel
                }
              </button>
            </div>
          </form>
        </div>
      </div>

      <!-- Vista previa -->
      @if (preview.data(); as data) {
        <div class="card shadow-sm" style="border: none">
          <div class="card-body p-4">
            <div class="d-flex flex-wrap justify-content-between align-items-center mb-3 gap-2">
              <h6 class="fw-bold mb-0 text-sufi-navy">
                Vista previa
                <span class="text-muted ms-2 fw-normal">
                  ({{ data.total }} resultado{{ data.total === 1 ? '' : 's' }})
                </span>
              </h6>
              <div class="d-flex align-items-center gap-2">
                <label class="form-label mb-0 small text-muted" for="rep-pagesize">Filas por página:</label>
                <select
                  id="rep-pagesize"
                  class="form-select form-select-sm"
                  style="width: auto"
                  [disabled]="preview.isPending()"
                  (change)="cambiarPageSize(+$any($event.target).value)"
                >
                  @for (opt of pageSizeOptions; track opt) {
                    <option [value]="opt" [selected]="opt === pageSize()">{{ opt }}</option>
                  }
                </select>
              </div>
            </div>

            <div class="table-responsive" style="max-height: 60vh">
              <table class="table table-striped table-hover table-sm mb-0">
                <thead class="position-sticky top-0 bg-light" style="z-index: 1">
                  <tr>
                    @for (col of data.columns; track $index) {
                      <th class="text-nowrap">{{ col }}</th>
                    }
                  </tr>
                </thead>
                <tbody>
                  @if (data.rows.length === 0) {
                    <tr>
                      <td [attr.colspan]="data.columns.length" class="text-center text-muted py-4">
                        Sin resultados para los filtros seleccionados.
                      </td>
                    </tr>
                  } @else {
                    @for (row of data.rows; track $index) {
                      <tr>
                        @for (cell of row; track $index) {
                          <td class="text-nowrap">{{ renderCell(cell) }}</td>
                        }
                      </tr>
                    }
                  }
                </tbody>
              </table>
            </div>

            @if (data.total > 0) {
              <div class="d-flex flex-wrap justify-content-between align-items-center mt-3 gap-2">
                <span class="text-muted small">Página {{ page() }} de {{ totalPages() }}</span>
                <div class="btn-group btn-group-sm" role="group">
                  <button type="button" class="btn btn-outline-secondary" (click)="cambiarPagina(1)"
                    [disabled]="page() <= 1 || preview.isPending()">
                    <i class="bi bi-chevron-double-left"></i>
                  </button>
                  <button type="button" class="btn btn-outline-secondary" (click)="cambiarPagina(page() - 1)"
                    [disabled]="page() <= 1 || preview.isPending()">
                    <i class="bi bi-chevron-left"></i>
                  </button>
                  <button type="button" class="btn btn-outline-secondary" (click)="cambiarPagina(page() + 1)"
                    [disabled]="page() >= totalPages() || preview.isPending()">
                    <i class="bi bi-chevron-right"></i>
                  </button>
                  <button type="button" class="btn btn-outline-secondary" (click)="cambiarPagina(totalPages())"
                    [disabled]="page() >= totalPages() || preview.isPending()">
                    <i class="bi bi-chevron-double-right"></i>
                  </button>
                </div>
              </div>
            }
          </div>
        </div>
      }
    </div>
  `,
})
export class ReportesPageComponent {
  private readonly api = inject(ApiClient);

  protected readonly tiposReporte = TIPOS_REPORTE;
  protected readonly estadosFiltrables = ESTADOS_PERFIL.filter((estado) => estado.value !== 3);
  protected readonly pageSizeOptions = PAGE_SIZE_OPTIONS;
  protected readonly programaMovilidad: number = PROGRAMA.MOVILIDAD;
  protected readonly programaConsumo: number = PROGRAMA.CONSUMO;
  protected readonly fechasObligatorias: boolean = true;

  protected readonly params = signal<FormState>({
    tipo: REPORTE_TIPO.HOJA_VIDA,
    programa: PROGRAMA.MOVILIDAD,
    subprograma: '',
    fecha_inicio: '',
    fecha_fin: '',
    cedula: '',
    estado: '',
  });
  protected readonly page = signal<number>(1);
  protected readonly pageSize = signal<number>(10);
  protected readonly errorFechas = signal<string>('');

  protected readonly ocultarPrograma = computed<boolean>(() =>
    TIPOS_SIN_PROGRAMA.includes(this.params().tipo),
  );
  protected readonly mostrarEstadoYCedula = computed<boolean>(
    () => this.params().tipo === REPORTE_TIPO.ESTADOS_PERFILES,
  );

  protected readonly subprogramasQuery = injectQuery(() => {
    const programa: number = this.params().programa;
    return {
      queryKey: [QUERY_KEYS.REPORTES, 'subprogramas', programa],
      queryFn: async () => {
        const url: string = `/asesor-consumo/subprogramas/${programa}`;
        const { data } = await this.api.get<Subprograma[]>(url);
        return data;
      },
      enabled: !this.ocultarPrograma() && programa === PROGRAMA.CONSUMO,
    };
  });

  protected readonly generar = injectGenerarReporte();
  protected readonly preview = injectObtenerPreviewReporte();

  protected readonly totalPages = computed<number>(() => {
    const data = this.preview.data();
    return data ? Math.max(1, Math.ceil(data.total / data.page_size)) : 1;
  });

  protected readonly subprogramaDisabled = computed<boolean>(
    () =>
      this.params().programa === PROGRAMA.MOVILIDAD ||
      this.subprogramasQuery.isLoading() ||
      (this.subprogramasQuery.data()?.length ?? 0) === 0,
  );

  constructor() {
    effect((onCleanup) => {
      if (!this.generar.isSuccess()) return;
      const timeoutId = setTimeout(() => this.generar.reset(), 10_000);
      onCleanup(() => clearTimeout(timeoutId));
    });
  }

  protected patch(cambios: Partial<FormState>): void {
    this.params.update((prev) => ({ ...prev, ...cambios }));
  }

  // Al cambiar tipo o programa se reinicia el subprograma (como el efecto del original).
  protected setTipo(valor: string): void {
    this.patch({ tipo: Number(valor) as ReporteTipo, subprograma: '' });
  }

  protected setPrograma(valor: string): void {
    this.patch({ programa: Number(valor), subprograma: '' });
  }

  protected setSubprograma(valor: string): void {
    this.patch({ subprograma: valor === '' ? '' : Number(valor) });
  }

  protected setEstado(valor: string): void {
    this.patch({ estado: valor === '' ? '' : Number(valor) });
  }

  protected onCedula(e: Event): void {
    const input = e.target as HTMLInputElement;
    const valor: string = input.value.replace(/\D/g, '');
    input.value = valor;
    this.patch({ cedula: valor });
  }

  protected renderCell(value: string | number | boolean | null): string {
    return renderCell(value);
  }

  private validarFechas(): boolean {
    this.errorFechas.set('');
    if (!this.fechasObligatorias) return true;
    const { fecha_inicio, fecha_fin } = this.params();
    if (!fecha_inicio || !fecha_fin) {
      this.errorFechas.set('Selecciona fecha inicio y fecha fin.');
      return false;
    }
    if (fecha_inicio >= fecha_fin) {
      this.errorFechas.set('La fecha inicio debe ser menor que la fecha fin.');
      return false;
    }
    return true;
  }

  private buildBaseParams(): ReporteParams {
    const params: FormState = this.params();
    const ocultar: boolean = this.ocultarPrograma();
    const mostrar: boolean = this.mostrarEstadoYCedula();
    return {
      tipo: params.tipo,
      programa: ocultar ? 1 : params.programa,
      subprograma: ocultar ? null : params.subprograma === '' ? null : Number(params.subprograma),
      fecha_inicio: params.fecha_inicio || undefined,
      fecha_fin: params.fecha_fin || undefined,
      cedula: mostrar && params.cedula ? params.cedula : undefined,
      estado: mostrar && params.estado !== '' ? Number(params.estado) : undefined,
    };
  }

  protected handleGenerarExcel(e: Event): void {
    e.preventDefault();
    if (!this.validarFechas()) return;
    this.generar.mutate(this.buildBaseParams());
  }

  protected handleGenerarPreview(): void {
    if (!this.validarFechas()) return;
    this.page.set(1);
    this.preview.mutate({ ...this.buildBaseParams(), page: 1, page_size: this.pageSize() });
  }

  protected cambiarPagina(nuevaPagina: number): void {
    if (nuevaPagina < 1 || nuevaPagina > this.totalPages()) return;
    this.page.set(nuevaPagina);
    this.preview.mutate({ ...this.buildBaseParams(), page: nuevaPagina, page_size: this.pageSize() });
  }

  protected cambiarPageSize(nuevoSize: number): void {
    this.pageSize.set(nuevoSize);
    this.page.set(1);
    this.preview.mutate({ ...this.buildBaseParams(), page: 1, page_size: nuevoSize });
  }
}

// FrontEndReact_V1.1/sufiatulado-app/src/pages/reportes/ReportesPage.tsx
import { useEffect, useMemo, useState } from 'react';
import { Alert, Button, ButtonGroup, Card, Col, Form, Row, Spinner, Table } from 'react-bootstrap';
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../../shared/api/client';
import { PageHeader } from '../../shared/ui/components/PageHeader';
import { PROGRAMA, QUERY_KEYS } from '../../shared/config/constants';
import { useGenerarReporte, useObtenerPreviewReporte } from '../../features/reportes/model/useReportes';
import { REPORTE_TIPO, type ReporteTipo } from '../../features/reportes/model/types';
import type { Subprograma } from '../../shared/api/catalogos';

interface FormState {
  tipo: ReporteTipo;
  programa: number;
  subprograma: number | '';
  fecha_inicio: string;
  fecha_fin: string;
  cedula: string;
  estado: number | '';
}

const TIPOS_REPORTE: ReadonlyArray<{ value: ReporteTipo; label: string }> = [
  { value: REPORTE_TIPO.HOJA_VIDA, label: 'Hoja de vida' },
  { value: REPORTE_TIPO.INFO_LABORAL, label: 'Información laboral' },
  { value: REPORTE_TIPO.PLANTILLA_PARTICIPANTES, label: 'Plantilla participantes' },
  { value: REPORTE_TIPO.INFO_TRIBUTARIA, label: 'Información tributaria' },
  { value: REPORTE_TIPO.USUARIOS_MIGRADOS, label: 'Usuarios migrados' },
  { value: REPORTE_TIPO.DEFAULT, label: 'Listado básico' },
  { value: REPORTE_TIPO.ESTADOS_PERFILES, label: 'Estados de perfiles' },
];

const ESTADOS_PERFIL: ReadonlyArray<{ value: number; label: string }> = [
  { value: 3, label: 'Todos' },
  { value: 0, label: 'Incompleto' },
  { value: 1, label: 'Completo' },
  { value: 2, label: 'Pendiente por documentación' },
];

const PAGE_SIZE_OPTIONS: ReadonlyArray<number> = [10, 20, 30];

function renderCell(value: string | number | boolean | null): string {
  if (value === null || value === undefined) return '';
  if (typeof value === 'boolean') return value ? 'Sí' : 'No';
  return String(value);
}

export function ReportesPage() {
  const [params, setParams] = useState<FormState>({
    tipo: REPORTE_TIPO.HOJA_VIDA,
    programa: PROGRAMA.MOVILIDAD,
    subprograma: '',
    fecha_inicio: '',
    fecha_fin: '',
    cedula: '',
    estado: '',
  });

  const [page, setPage] = useState<number>(1);
  const [pageSize, setPageSize] = useState<number>(10);

  const ocultarPrograma: boolean = useMemo(() => {
    const tiposSinPrograma: readonly ReporteTipo[] = [
      REPORTE_TIPO.INFO_LABORAL,
      REPORTE_TIPO.INFO_TRIBUTARIA,
      REPORTE_TIPO.USUARIOS_MIGRADOS,
    ];
    return tiposSinPrograma.includes(params.tipo);
  }, [params.tipo]);
  const mostrarEstadoYCedula: boolean = params.tipo === REPORTE_TIPO.ESTADOS_PERFILES;
  const fechasObligatorias: boolean = true;
  const [errorFechas, setErrorFechas] = useState<string>('');

  const subprogramasQuery = useQuery({
    queryKey: [QUERY_KEYS.REPORTES, 'subprogramas', params.programa],
    queryFn: async () => {
      const url: string = `/asesor-consumo/subprogramas/${params.programa}`;
      const { data } = await apiClient.get<Subprograma[]>(url);
      return data;
    },
    enabled: !ocultarPrograma && params.programa === PROGRAMA.CONSUMO,
  });

  useEffect(() => {
    setParams((prev) => ({ ...prev, subprograma: '' }));
  }, [params.programa, params.tipo]);

  const generar = useGenerarReporte();
  const preview = useObtenerPreviewReporte();

  useEffect(() => {
    if (!generar.isSuccess) return;
    const timeoutId = setTimeout(() => generar.reset(), 10_000);
    return () => clearTimeout(timeoutId);
  }, [generar.isSuccess, generar.reset]);

  const totalPages: number = preview.data
    ? Math.max(1, Math.ceil(preview.data.total / preview.data.page_size))
    : 1;

  const validarFechas = (): boolean => {
    setErrorFechas('');
    if (!fechasObligatorias) return true;
    if (!params.fecha_inicio || !params.fecha_fin) {
      setErrorFechas('Selecciona fecha inicio y fecha fin.');
      return false;
    }
    if (params.fecha_inicio >= params.fecha_fin) {
      setErrorFechas('La fecha inicio debe ser menor que la fecha fin.');
      return false;
    }
    return true;
  };

  const buildBaseParams = () => ({
    tipo: params.tipo,
    programa: ocultarPrograma ? 1 : params.programa,
    subprograma: ocultarPrograma ? null : (params.subprograma === '' ? null : Number(params.subprograma)),
    fecha_inicio: params.fecha_inicio || undefined,
    fecha_fin: params.fecha_fin || undefined,
    cedula: mostrarEstadoYCedula && params.cedula ? params.cedula : undefined,
    estado: mostrarEstadoYCedula && params.estado !== '' ? Number(params.estado) : undefined,
  });

  const handleGenerarExcel = (e: React.FormEvent<HTMLFormElement>): void => {
    e.preventDefault();
    if (!validarFechas()) return;
    generar.mutate(buildBaseParams());
  };

  const handleGenerarPreview = (): void => {
    if (!validarFechas()) return;
    setPage(1);
    preview.mutate({ ...buildBaseParams(), page: 1, page_size: pageSize });
  };

  const cambiarPagina = (nuevaPagina: number): void => {
    if (nuevaPagina < 1 || nuevaPagina > totalPages) return;
    setPage(nuevaPagina);
    preview.mutate({ ...buildBaseParams(), page: nuevaPagina, page_size: pageSize });
  };

  const cambiarPageSize = (nuevoSize: number): void => {
    setPageSize(nuevoSize);
    setPage(1);
    preview.mutate({ ...buildBaseParams(), page: 1, page_size: nuevoSize });
  };

  const subprogramaDisabled: boolean =
    params.programa === PROGRAMA.MOVILIDAD
    || subprogramasQuery.isLoading
    || (subprogramasQuery.data?.length ?? 0) === 0;

  const renderConfigForm = () => (
    <Card className="shadow-sm mb-3" style={{ border: 'none' }}>
      <Card.Body className="p-4">
        <Form onSubmit={handleGenerarExcel}>
          <h6 className="fw-bold mb-3 text-sufi-navy">Configurar reporte</h6>

          {generar.isError && (
            <Alert variant="danger" className="py-2">
              <i className="bi bi-exclamation-circle me-2" />
              Error al generar el reporte. Verifica los filtros e intenta de nuevo.
            </Alert>
          )}
          {generar.isSuccess && (
            <Alert variant="success" className="py-2">
              <i className="bi bi-check-circle me-2" />
              Reporte generado y descargado correctamente.
            </Alert>
          )}
          {preview.isError && (
            <Alert variant="danger" className="py-2">
              <i className="bi bi-exclamation-circle me-2" />
              Error al obtener la vista previa. Verifica los filtros e intenta de nuevo.
            </Alert>
          )}

          <Row className="g-3">
            <Col md={6}>
              <Form.Group>
                <Form.Label>Tipo de reporte</Form.Label>
                <Form.Select
                  value={params.tipo}
                  onChange={(e) => setParams((prev) => ({ ...prev, tipo: Number(e.target.value) as ReporteTipo }))}
                >
                  {TIPOS_REPORTE.map((tipoReporte) => (
                    <option key={tipoReporte.value} value={tipoReporte.value}>{tipoReporte.label}</option>
                  ))}
                </Form.Select>
              </Form.Group>
            </Col>

            {!ocultarPrograma && (
              <Col md={6}>
                <Form.Group>
                  <Form.Label>Programa</Form.Label>
                  <Form.Select
                    value={params.programa}
                    onChange={(e) => setParams((prev) => ({ ...prev, programa: Number(e.target.value) }))}
                  >
                    <option value={PROGRAMA.MOVILIDAD}>Movilidad (Vehículos)</option>
                    <option value={PROGRAMA.CONSUMO}>Consumo y Servicios</option>
                  </Form.Select>
                </Form.Group>
              </Col>
            )}

            {!ocultarPrograma && (
              <Col md={6}>
                <Form.Group>
                  <Form.Label>Subprograma</Form.Label>
                  <Form.Select
                    value={params.subprograma}
                    onChange={(e) => setParams((prev) => ({ ...prev, subprograma: e.target.value === '' ? '' : Number(e.target.value) }))}
                    disabled={subprogramaDisabled}
                  >
                    <option value="">Todos</option>
                    {(subprogramasQuery.data ?? []).map((subprograma) => (
                      <option key={subprograma.cspid} value={subprograma.cspid}>{subprograma.cspid_nombre}</option>
                    ))}
                  </Form.Select>
                </Form.Group>
              </Col>
            )}

            <Col xs={12} md={6}>
              <Row className="g-2">
                <Col xs={12} md={6}>
                  <Form.Group>
                    <Form.Label>
                      Fecha inicio
                      {fechasObligatorias && <span className="text-danger ms-1">*</span>}
                    </Form.Label>
                    <Form.Control
                      type="date"
                      value={params.fecha_inicio}
                      max={params.fecha_fin || undefined}
                      required={fechasObligatorias}
                      onChange={(e) => setParams((prev) => ({ ...prev, fecha_inicio: e.target.value }))}
                    />
                  </Form.Group>
                </Col>
                <Col xs={12} md={6}>
                  <Form.Group>
                    <Form.Label>
                      Fecha fin
                      {fechasObligatorias && <span className="text-danger ms-1">*</span>}
                    </Form.Label>
                    <Form.Control
                      type="date"
                      value={params.fecha_fin}
                      min={params.fecha_inicio || undefined}
                      required={fechasObligatorias}
                      onChange={(e) => setParams((prev) => ({ ...prev, fecha_fin: e.target.value }))}
                    />
                  </Form.Group>
                </Col>
              </Row>
            </Col>
            {errorFechas && (
              <Col xs={12}>
                <Alert variant="warning" className="py-2 mb-0">
                  <i className="bi bi-exclamation-triangle me-2" />{errorFechas}
                </Alert>
              </Col>
            )}

            {mostrarEstadoYCedula && (
              <>
                <Col md={6}>
                  <Form.Group>
                    <Form.Label>Cédula</Form.Label>
                    <Form.Control
                      type="text"
                      placeholder="Solo dígitos"
                      value={params.cedula}
                      onChange={(e) => setParams((prev) => ({ ...prev, cedula: e.target.value.replace(/\D/g, '') }))}
                    />
                  </Form.Group>
                </Col>
                <Col md={6}>
                  <Form.Group>
                    <Form.Label>Estado</Form.Label>
                    <Form.Select
                      value={params.estado}
                      onChange={(e) => setParams((prev) => ({ ...prev, estado: e.target.value === '' ? '' : Number(e.target.value) }))}
                    >
                      <option value="">Todos</option>
                      {ESTADOS_PERFIL.filter((estado) => estado.value !== 3).map((estado) => (
                        <option key={estado.value} value={estado.value}>{estado.label}</option>
                      ))}
                    </Form.Select>
                  </Form.Group>
                </Col>
              </>
            )}
          </Row>

          <div className="mt-4 d-flex flex-wrap gap-2">
            <Button type="button" variant="primary" onClick={handleGenerarPreview} disabled={preview.isPending}>
              {preview.isPending ? (
                <><Spinner size="sm" animation="border" className="me-2" />Generando…</>
              ) : (
                <><i className="bi bi-eye me-2" />Generar</>
              )}
            </Button>
            <Button type="submit" variant="success" disabled={generar.isPending}>
              {generar.isPending ? (
                <><Spinner size="sm" animation="border" className="me-2" />Descargando…</>
              ) : (
                <><i className="bi bi-file-earmark-excel me-2" />Descargar Excel</>
              )}
            </Button>
          </div>
        </Form>
      </Card.Body>
    </Card>
  );

  const renderFilas = () => {
    if (!preview.data) return null;
    if (preview.data.rows.length === 0) {
      return (
        <tr>
          <td colSpan={preview.data.columns.length} className="text-center text-muted py-4">
            Sin resultados para los filtros seleccionados.
          </td>
        </tr>
      );
    }
    return preview.data.rows.map((row, i) => (
      <tr key={i}>
        {row.map((cell, j) => <td key={j} className="text-nowrap">{renderCell(cell)}</td>)}
      </tr>
    ));
  };

  const renderPreview = () => {
    if (!preview.data) return null;
    return (
      <Card className="shadow-sm" style={{ border: 'none' }}>
        <Card.Body className="p-4">
          <div className="d-flex flex-wrap justify-content-between align-items-center mb-3 gap-2">
            <h6 className="fw-bold mb-0 text-sufi-navy">
              Vista previa
              <span className="text-muted ms-2 fw-normal">
                ({preview.data.total} resultado{preview.data.total === 1 ? '' : 's'})
              </span>
            </h6>
            <div className="d-flex align-items-center gap-2">
              <Form.Label className="mb-0 small text-muted">Filas por página:</Form.Label>
              <Form.Select
                size="sm" style={{ width: 'auto' }} value={pageSize}
                onChange={(e) => cambiarPageSize(Number(e.target.value))}
                disabled={preview.isPending}
              >
                {PAGE_SIZE_OPTIONS.map((opt) => <option key={opt} value={opt}>{opt}</option>)}
              </Form.Select>
            </div>
          </div>

          <div className="table-responsive" style={{ maxHeight: '60vh' }}>
            <Table striped hover size="sm" className="mb-0">
              <thead className="position-sticky top-0 bg-light" style={{ zIndex: 1 }}>
                <tr>
                  {preview.data.columns.map((col) => <th key={col} className="text-nowrap">{col}</th>)}
                </tr>
              </thead>
              <tbody>{renderFilas()}</tbody>
            </Table>
          </div>

          {preview.data.total > 0 && (
            <div className="d-flex flex-wrap justify-content-between align-items-center mt-3 gap-2">
              <span className="text-muted small">Página {page} de {totalPages}</span>
              <ButtonGroup size="sm">
                <Button variant="outline-secondary" onClick={() => cambiarPagina(1)} disabled={page <= 1 || preview.isPending}>
                  <i className="bi bi-chevron-double-left" />
                </Button>
                <Button variant="outline-secondary" onClick={() => cambiarPagina(page - 1)} disabled={page <= 1 || preview.isPending}>
                  <i className="bi bi-chevron-left" />
                </Button>
                <Button variant="outline-secondary" onClick={() => cambiarPagina(page + 1)} disabled={page >= totalPages || preview.isPending}>
                  <i className="bi bi-chevron-right" />
                </Button>
                <Button variant="outline-secondary" onClick={() => cambiarPagina(totalPages)} disabled={page >= totalPages || preview.isPending}>
                  <i className="bi bi-chevron-double-right" />
                </Button>
              </ButtonGroup>
            </div>
          )}
        </Card.Body>
      </Card>
    );
  };

  return (
    <div>
      <PageHeader
        title="Reportes"
        subtitle="Genera vista previa o descarga en Excel"
        icon="bi-file-earmark-bar-graph"
      />
      {renderConfigForm()}
      {renderPreview()}
    </div>
  );
}
