// FrontEndAngular_V1.1/frontend-app/src/shared/ui/components/estado-switch.component.ts
import { ChangeDetectionStrategy, Component, input, model } from '@angular/core';

/** Interruptor de estado Activo/Inactivo. Soporta `[(checked)]`. */
@Component({
  selector: 'app-estado-switch',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (compact()) {
      <div
        class="form-check form-switch mb-0"
        [class]="className()"
        [title]="checked() ? labelActivo() : labelInactivo()"
        style="transform: scale(1.3); transform-origin: center center"
      >
        <input
          class="form-check-input"
          type="checkbox"
          role="switch"
          [id]="id()"
          [checked]="checked()"
          [disabled]="disabled()"
          (change)="cambiar($any($event.target).checked)"
        />
      </div>
    } @else {
      <div
        class="d-inline-flex align-items-center gap-3 px-4 py-3 rounded-3 border"
        [class]="className()"
        [style.background]="checked() ? 'rgba(25, 135, 84, 0.07)' : 'rgba(108, 117, 125, 0.07)'"
        [style.border-color]="checked() ? 'rgba(25, 135, 84, 0.25)' : 'rgba(108, 117, 125, 0.2)'"
        [style.cursor]="disabled() ? 'not-allowed' : 'pointer'"
        style="transition: background 0.2s ease; min-width: 190px"
        (click)="onContenedorClick()"
        role="group"
        aria-label="Estado"
      >
        <div
          class="form-check form-switch mb-0"
          style="flex-shrink: 0; transform: scale(1.35); transform-origin: left center"
        >
          <input
            class="form-check-input"
            type="checkbox"
            role="switch"
            [id]="id()"
            [checked]="checked()"
            [disabled]="disabled()"
            (click)="$event.stopPropagation()"
            (change)="cambiar($any($event.target).checked)"
          />
        </div>
        <div class="d-flex flex-column" style="line-height: 1.3">
          <small
            class="text-muted"
            style="font-size: 0.72rem; text-transform: uppercase; letter-spacing: 0.05em; font-weight: 600"
          >
            Estado
          </small>
          <span
            class="fw-semibold"
            [style.color]="checked() ? '#198754' : '#6c757d'"
            style="font-size: 1rem; transition: color 0.2s ease"
          >
            @if (checked()) {
              <i class="bi bi-check-circle-fill me-1" style="font-size: 0.85rem"></i>{{ labelActivo() }}
            } @else {
              <i class="bi bi-dash-circle me-1" style="font-size: 0.85rem"></i>{{ labelInactivo() }}
            }
          </span>
        </div>
      </div>
    }
  `,
})
export class EstadoSwitchComponent {
  readonly id = input.required<string>();
  readonly checked = model.required<boolean>();
  readonly labelActivo = input<string>('Activo');
  readonly labelInactivo = input<string>('Inactivo');
  readonly compact = input<boolean>(false);
  readonly disabled = input<boolean>(false);
  readonly className = input<string>('');

  protected onContenedorClick(): void {
    if (!this.disabled()) this.cambiar(!this.checked());
  }

  protected cambiar(valor: boolean): void {
    this.checked.set(valor);
  }
}

// FrontEndReact_V1.1/frontend-app/src/shared/ui/components/EstadoSwitch.tsx
import { Form } from 'react-bootstrap';

interface EstadoSwitchProps {
  id: string;
  checked: boolean;
  onChange: (value: boolean) => void;
  labelActivo?: string;
  labelInactivo?: string;
  compact?: boolean;
  disabled?: boolean;
  className?: string;
}

export function EstadoSwitch({
  id,
  checked,
  onChange,
  labelActivo = 'Activo',
  labelInactivo = 'Inactivo',
  compact = false,
  disabled = false,
  className = '',
}: EstadoSwitchProps) {
  if (compact) {
    return (
      <Form.Check
        type="switch"
        id={id}
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        disabled={disabled}
        className={`mb-0 ${className}`}
        title={checked ? labelActivo : labelInactivo}
        style={{ transform: 'scale(1.3)', transformOrigin: 'center center' }}
      />
    );
  }
  return (
    <div
      className={`d-inline-flex align-items-center gap-3 px-4 py-3 rounded-3 border ${className}`}
      style={{
        background: checked
          ? 'rgba(25, 135, 84, 0.07)'
          : 'rgba(108, 117, 125, 0.07)',
        borderColor: checked
          ? 'rgba(25, 135, 84, 0.25) !important'
          : 'rgba(108, 117, 125, 0.2) !important',
        transition: 'background 0.2s ease',
        cursor: disabled ? 'not-allowed' : 'pointer',
        minWidth: 190,
      }}
      onClick={() => !disabled && onChange(!checked)}
      role="group"
      aria-label="Estado"
    >
      <Form.Check
        type="switch"
        id={id}
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        disabled={disabled}
        onClick={(e) => e.stopPropagation()}
        className="mb-0"
        style={{ flexShrink: 0, transform: 'scale(1.35)', transformOrigin: 'left center' }}
      />
      <div className="d-flex flex-column" style={{ lineHeight: 1.3 }}>
        <small className="text-muted" style={{ fontSize: '0.72rem', textTransform: 'uppercase', letterSpacing: '0.05em', fontWeight: 600 }}>
          Estado
        </small>
        <span
          className="fw-semibold"
          style={{
            fontSize: '1rem',
            color: checked ? '#198754' : '#6c757d',
            transition: 'color 0.2s ease',
          }}
        >
          {checked ? (
            <><i className="bi bi-check-circle-fill me-1" style={{ fontSize: '0.85rem' }} />{labelActivo}</>
          ) : (
            <><i className="bi bi-dash-circle me-1" style={{ fontSize: '0.85rem' }} />{labelInactivo}</>
          )}
        </span>
      </div>
    </div>
  );
}
