// FrontEndReact_V1.1/frontend-app/src/pages/admin/BancosAdminPage.tsx
import { CatalogoCrudPage } from '../../shared/ui/components/CatalogoCrudPage';
import type { FormValues } from '../../shared/ui/components/CatalogoCrudPage';
import {
  useActualizarAdminBanco,
  useAdminBancosList,
  useCrearAdminBanco,
  useEliminarAdminBanco,
} from '../../features/admin-bancos/model/useAdminBancos';
import type {
  AdminBancoFormPayload,
  AdminBancoListItem,
} from '../../features/admin-bancos/model/types';

export function BancosAdminPage() {
  const actualizarMut = useActualizarAdminBanco();
  return (
    <CatalogoCrudPage<AdminBancoListItem, AdminBancoFormPayload>
      title="Administrar Bancos"
      icon="bi-bank2"
      singular="Banco"
      backTo="/admin/catalogos"
      idOf={(i) => i.tid}
      columns={[
        { header: 'Código', width: 100, cell: (i) => <code>{i.tid}</code> },
        { header: 'Nombre', className: 'fw-semibold', cell: (i) => i.nombre },
        {
          header: 'Código bancario', width: 200,
          cell: (i) => (i.codigo ? <code className="small">{i.codigo}</code> : <span className="text-muted small">—</span>),
        },
      ]}
      fields={[
        { key: 'nombre', label: 'Nombre', required: true, maxLength: 200, col: 8, placeholder: 'Ej: Bancolombia' },
        { key: 'codigo', label: 'Código bancario', maxLength: 10, col: 4, placeholder: 'Opcional' },
      ]}
      initForm={{ nombre: '', codigo: '' }}
      itemToForm={(i) => ({ nombre: i.nombre, codigo: i.codigo ?? '' })}
      toPayload={(f: FormValues): AdminBancoFormPayload => ({
        nombre: f.nombre.trim(),
        codigo: f.codigo.trim() === '' ? null : f.codigo.trim(),
      })}
      validate={(f) => (f.nombre.trim() ? null : 'El nombre del banco es obligatorio')}
      deleteWarning={
        <>¿Confirma eliminar el banco? Esta acción es <strong>permanente</strong>.<br />
          <small className="text-muted">Si está referenciado en perfiles, la operación será rechazada.</small></>
      }
      useList={useAdminBancosList}
      crearMut={useCrearAdminBanco()}
      actualizar={(tid, payload) => actualizarMut.mutateAsync({ tid, payload })}
      actualizarPending={actualizarMut.isPending}
      eliminarMut={useEliminarAdminBanco()}
    />
  );
}

// FrontEndAngular_V1.1/sufiatulado-app/src/pages/admin/bancos-admin-page.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import {
  CatalogoCrudComponent,
  type AvisoBorrado,
  type CampoCatalogo,
  type ColumnaCatalogo,
} from '../../shared/ui/components/catalogo-crud/catalogo-crud.component';
import { injectCatalogoCrud, type FormValues } from '../../shared/ui/components/catalogo-crud/catalogo-crud';
import {
  injectActualizarAdminBanco,
  injectAdminBancosList,
  injectCrearAdminBanco,
  injectEliminarAdminBanco,
} from '../../features/admin-bancos/model/queries';
import type { AdminBancoFormPayload, AdminBancoListItem } from '../../features/admin-bancos/model/types';

const COLUMNAS: ColumnaCatalogo<AdminBancoListItem>[] = [
  { header: 'Código', width: 100, tipo: 'code', valor: (i) => i.tid },
  { header: 'Nombre', className: 'fw-semibold', tipo: 'text', valor: (i) => i.nombre },
  { header: 'Código bancario', width: 200, tipo: 'codeOpcional', valor: (i) => i.codigo },
];

const CAMPOS: CampoCatalogo[] = [
  { key: 'nombre', label: 'Nombre', required: true, maxLength: 200, col: 8, placeholder: 'Ej: Bancolombia' },
  { key: 'codigo', label: 'Código bancario', maxLength: 10, col: 4, placeholder: 'Opcional' },
];

const AVISO: AvisoBorrado = { objeto: 'el banco', nota: 'Si está referenciado en perfiles, la operación será rechazada.' };

@Component({
  selector: 'app-bancos-admin-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CatalogoCrudComponent],
  template: `
    <app-catalogo-crud
      [crud]="crud"
      title="Administrar Bancos"
      icon="bi-bank2"
      backTo="/admin/catalogos"
      [columns]="columnas"
      [fields]="campos"
      [deleteWarning]="aviso"
    />
  `,
})
export class BancosAdminPageComponent {
  protected readonly columnas = COLUMNAS;
  protected readonly campos = CAMPOS;
  protected readonly aviso = AVISO;

  private readonly actualizarMut = injectActualizarAdminBanco();

  protected readonly crud = injectCatalogoCrud<AdminBancoListItem, AdminBancoFormPayload>({
    singular: 'Banco',
    idOf: (item) => item.tid,
    initForm: { nombre: '', codigo: '' },
    itemToForm: (i) => ({ nombre: i.nombre, codigo: i.codigo ?? '' }),
    toPayload: (f: FormValues): AdminBancoFormPayload => ({
      nombre: f['nombre'].trim(),
      codigo: f['codigo'].trim() === '' ? null : f['codigo'].trim(),
    }),
    validate: (f) => (f['nombre'].trim() ? null : 'El nombre del banco es obligatorio'),
    list: (q) => injectAdminBancosList(q),
    crear: injectCrearAdminBanco(),
    actualizar: (tid, payload) => this.actualizarMut.mutateAsync({ tid, payload }),
    actualizarPending: this.actualizarMut.isPending,
    eliminar: injectEliminarAdminBanco(),
  });
}
