// FrontEndReact_V1.1/frontend-app/src/pages/admin/PasswordTemporalResultadoModal.tsx
import { Button, Modal } from 'react-bootstrap';
import type { PasswordTemporalResultado } from '../../features/admin-usuarios/model/types';

interface Props {
  resultado: PasswordTemporalResultado | null;
  onCerrar: () => void;
}

// AP-0047: muestra la clave temporal generada una unica vez (solo viaja en la
// respuesta de emision; el sistema persiste unicamente su hash).
export function PasswordTemporalResultadoModal({ resultado, onCerrar }: Props) {
  return (
    <Modal show={resultado !== null} onHide={onCerrar} centered>
      <Modal.Header closeButton>
        <Modal.Title as="h6">
          <i className="bi bi-key me-2" />
          Contrasena temporal generada
        </Modal.Title>
      </Modal.Header>
      <Modal.Body>
        <p className="small text-muted mb-3">
          Entregala a <strong>{resultado?.usuario}</strong> por un canal seguro. Se
          muestra una sola vez, vence en{' '}
          {resultado?.ttl_minutos} minutos y el usuario debera definir su contrasena
          personal al ingresar.
        </p>
        <div className="p-3 bg-light border rounded text-center">
          <code className="fs-5 user-select-all">{resultado?.password_temporal}</code>
        </div>
      </Modal.Body>
      <Modal.Footer>
        <Button variant="secondary" size="sm" onClick={onCerrar}>
          Cerrar
        </Button>
      </Modal.Footer>
    </Modal>
  );
}

// FrontEndAngular_V1.1/sufiatulado-app/src/pages/admin/password-temporal-resultado-modal.component.ts
import { ChangeDetectionStrategy, Component, input, output } from '@angular/core';
import { ModalComponent } from '../../shared/ui/components/modal.component';
import type { PasswordTemporalResultado } from '../../features/admin-usuarios/model/types';

// AP-0047: muestra la clave temporal generada una unica vez (solo viaja en la
// respuesta de emision; el sistema persiste unicamente su hash).
@Component({
  selector: 'app-password-temporal-resultado-modal',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [ModalComponent],
  template: `
    <app-modal [show]="resultado() !== null" [centered]="true" (hide)="cerrar.emit()">
      <div class="modal-header">
        <h6 class="modal-title">
          <i class="bi bi-key me-2"></i>
          Contrasena temporal generada
        </h6>
        <button type="button" class="btn-close" aria-label="Close" (click)="cerrar.emit()"></button>
      </div>
      <div class="modal-body">
        <p class="small text-muted mb-3">
          Entregala a <strong>{{ resultado()?.usuario }}</strong> por un canal seguro. Se
          muestra una sola vez, vence en
          {{ resultado()?.ttl_minutos }} minutos y el usuario debera definir su contrasena
          personal al ingresar.
        </p>
        <div class="p-3 bg-light border rounded text-center">
          <code class="fs-5 user-select-all">{{ resultado()?.password_temporal }}</code>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary btn-sm" (click)="cerrar.emit()">Cerrar</button>
      </div>
    </app-modal>
  `,
})
export class PasswordTemporalResultadoModalComponent {
  readonly resultado = input<PasswordTemporalResultado | null>(null);
  readonly cerrar = output<void>();
}
