// FrontEndReact_V1.1/frontend-app/src/shared/ui/components/MetroTileToggle.tsx
import { useState, useId, type ReactNode, type CSSProperties } from 'react';
import { motion, AnimatePresence, type Variants } from 'framer-motion';
import '../../../styles/components/MetroTileToggle.scss';

export type MetroTileSize = 'small' | 'medium' | 'wide';

export type MetroTileColor =
  | 'red'
  | 'navy'
  | 'blue'
  | 'gold'
  | 'yellow'
  | 'dark-navy'
  | 'teal'
  | 'green'
  | 'gray'
  | 'orange'
  | 'orange-deep'
  | 'amber'
  | 'cyan'
  | 'cyan-deep'
  | 'purple'
  | 'violet'
  | 'magenta';

interface CustomColor {
  base: string;
  dark: string;
}

interface MetroTileToggleProps {
  title: string;
  icon: string;
  children: ReactNode;
  subtitle?: string;
  color?: MetroTileColor;
  customColor?: CustomColor;
  size?: MetroTileSize;
  badge?: number | string | null;
  defaultOpen?: boolean;
  closeLabel?: string;
  className?: string;
  onSave?: () => void;
  saveLabel?: string;
  saving?: boolean;
  saveDisabled?: boolean;
}

const HEADER_VARIANTS: Variants = {
  rest:    { scale: 1,    y: 0 },
  hover:   { scale: 1.02, y: -2 },
  pressed: { scale: 0.98 },
};

const BODY_VARIANTS: Variants = {
  collapsed: {
    height: 0,
    opacity: 0,
    transition: { duration: 0.32, ease: [0.22, 1, 0.36, 1] },
  },
  expanded: {
    height: 'auto',
    opacity: 1,
    transition: { duration: 0.42, ease: [0.22, 1, 0.36, 1] },
  },
};

const CONTENT_VARIANTS: Variants = {
  hidden:  { opacity: 0, y: 12 },
  visible: {
    opacity: 1,
    y: 0,
    transition: { duration: 0.32, ease: [0.22, 1, 0.36, 1], delay: 0.08 },
  },
  exit:    { opacity: 0, y: 6, transition: { duration: 0.18 } },
};

interface MetroTileSaveButtonProps {
  onSave: () => void;
  label: string;
  saving: boolean;
  disabled: boolean;
}

function MetroTileSaveButton({ onSave, label, saving, disabled }: MetroTileSaveButtonProps) {
  return (
    <button
      type="button"
      className="metro-tile__save"
      onClick={onSave}
      disabled={saving || disabled}
    >
      {saving ? (
        <>
          <span
            className="spinner-border spinner-border-sm"
            role="status"
            aria-hidden="true"
          />
          Guardando…
        </>
      ) : (
        <>
          <i className="bi bi-check-lg" />
          {label}
        </>
      )}
    </button>
  );
}

interface MetroTileFooterProps {
  onClose: () => void;
  closeLabel: string;
  onSave?: () => void;
  saveLabel: string;
  saving: boolean;
  saveDisabled: boolean;
}

function MetroTileFooter({
  onClose,
  closeLabel,
  onSave,
  saveLabel,
  saving,
  saveDisabled,
}: MetroTileFooterProps) {
  return (
    <div className="metro-tile__footer">
      {onSave && (
        <MetroTileSaveButton
          onSave={onSave}
          label={saveLabel}
          saving={saving}
          disabled={saveDisabled}
        />
      )}
      <button type="button" className="metro-tile__close" onClick={onClose}>
        <i className="bi bi-x-lg" />
        {closeLabel}
      </button>
    </div>
  );
}

export function MetroTileToggle({
  title,
  icon,
  children,
  subtitle,
  color = 'red',
  customColor,
  size = 'medium',
  badge = null,
  defaultOpen = false,
  closeLabel = 'Cerrar',
  className = '',
  onSave,
  saveLabel = 'Guardar',
  saving = false,
  saveDisabled = false,
}: MetroTileToggleProps) {
  const [open, setOpen] = useState<boolean>(defaultOpen);
  const reactId: string = useId();
  const bodyId: string = `metro-tile-body-${reactId}`;

  const colorClass: string = customColor ? 'has-custom-color' : `metro-tile--${color}`;
  const sizeClass: string = `metro-tile--${size}`;

  const customStyle: CSSProperties | undefined = customColor
    ? ({
        '--metro-tile-color': customColor.base,
        '--metro-tile-color-dark': customColor.dark,
      } as CSSProperties)
    : undefined;

  const showBadge: boolean = badge !== null && badge !== undefined && badge !== '' && badge !== 0;

  return (
    <motion.div
      layout
      transition={{ layout: { duration: 0.42, ease: [0.22, 1, 0.36, 1] } }}
      className={`metro-tile ${colorClass} ${sizeClass} ${open ? 'is-open' : ''} ${className}`}
      style={customStyle}
    >
      <motion.button
        type="button"
        layout
        variants={HEADER_VARIANTS}
        initial="rest"
        animate="rest"
        whileHover="hover"
        whileTap="pressed"
        transition={{ type: 'spring', stiffness: 320, damping: 24 }}
        className="metro-tile__header"
        aria-expanded={open}
        aria-controls={bodyId}
        role="button"
        onClick={() => setOpen(prev => !prev)}
      >
        <span className="metro-tile__icon" aria-hidden="true">
          <i className={`bi ${icon}`} />
        </span>
        <span className="metro-tile__titles">
          <span className="metro-tile__title">{title}</span>
          {subtitle && <span className="metro-tile__subtitle">{subtitle}</span>}
        </span>
        {showBadge && <span className="metro-tile__badge">{badge}</span>}
        <span className="metro-tile__chevron" aria-hidden="true">
          <i className="bi bi-chevron-down" />
        </span>
      </motion.button>

      <AnimatePresence initial={false}>
        {open && (
          <motion.section
            key="body"
            id={bodyId}
            variants={BODY_VARIANTS}
            initial="collapsed"
            animate="expanded"
            exit="collapsed"
            className="metro-tile__body"
            aria-hidden={!open}
          >
            <motion.div
              variants={CONTENT_VARIANTS}
              initial="hidden"
              animate="visible"
              exit="exit"
              className="metro-tile__content"
            >
              {children}
            </motion.div>
            <MetroTileFooter
              onClose={() => setOpen(false)}
              closeLabel={closeLabel}
              onSave={onSave}
              saveLabel={saveLabel}
              saving={saving}
              saveDisabled={saveDisabled}
            />
          </motion.section>
        )}
      </AnimatePresence>
    </motion.div>
  );
}

// FrontEndAngular_V1.1/sufiatulado-app/src/shared/ui/components/metro-tile-toggle.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  computed,
  inject,
  input,
  output,
  signal,
} from '@angular/core';

export type MetroTileSize = 'small' | 'medium' | 'wide';

export type MetroTileColor =
  | 'red'
  | 'navy'
  | 'blue'
  | 'gold'
  | 'yellow'
  | 'dark-navy'
  | 'teal'
  | 'green'
  | 'gray'
  | 'orange'
  | 'orange-deep'
  | 'amber'
  | 'cyan'
  | 'cyan-deep'
  | 'purple'
  | 'violet'
  | 'magenta';

export interface MetroTileCustomColor {
  base: string;
  dark: string;
}

let secuencia = 0;

/** Duraciones/curva equivalentes a las variantes de framer-motion del original. */
const DURACION_CIERRE_MS = 320;

/**
 * Tile tipo "Metro" desplegable (equivalente a `MetroTileToggle`). Las animaciones de
 * framer-motion se reemplazan por transiciones CSS (expansión con grid-template-rows,
 * fade/slide del contenido y escala del encabezado en hover/tap).
 */
@Component({
  selector: 'app-metro-tile-toggle',
  changeDetection: ChangeDetectionStrategy.OnPush,
  host: { style: 'display: contents' },
  template: `
    <div
      [class]="clases()"
      [style.--metro-tile-color]="customColor()?.base"
      [style.--metro-tile-color-dark]="customColor()?.dark"
    >
      <button
        type="button"
        class="metro-tile__header metro-tile__header--anim"
        [attr.aria-expanded]="open()"
        [attr.aria-controls]="bodyId"
        role="button"
        (click)="toggle()"
      >
        <span class="metro-tile__icon" aria-hidden="true">
          <i class="bi" [class]="icon()"></i>
        </span>
        <span class="metro-tile__titles">
          <span class="metro-tile__title">{{ title() }}</span>
          @if (subtitle()) {
            <span class="metro-tile__subtitle">{{ subtitle() }}</span>
          }
        </span>
        @if (showBadge()) {
          <span class="metro-tile__badge">{{ badge() }}</span>
        }
        <span class="metro-tile__chevron" aria-hidden="true">
          <i class="bi bi-chevron-down"></i>
        </span>
      </button>

      @if (rendered()) {
        <section
          [id]="bodyId"
          class="metro-tile__body metro-tile__body--anim"
          [class.is-expanded]="expanded()"
          [attr.aria-hidden]="!open()"
        >
          <div class="metro-tile__body-inner">
            <div class="metro-tile__content metro-tile__content--anim">
              <ng-content />
            </div>
            <div class="metro-tile__footer">
              @if (hasSave()) {
                <button
                  type="button"
                  class="metro-tile__save"
                  (click)="save.emit()"
                  [disabled]="saving() || saveDisabled()"
                >
                  @if (saving()) {
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    Guardando…
                  } @else {
                    <i class="bi bi-check-lg"></i>
                    {{ saveLabel() }}
                  }
                </button>
              }
              <button type="button" class="metro-tile__close" (click)="cerrar()">
                <i class="bi bi-x-lg"></i>
                {{ closeLabel() }}
              </button>
            </div>
          </div>
        </section>
      }
    </div>
  `,
  styles: `
    .metro-tile__header--anim {
      transition:
        transform 0.25s cubic-bezier(0.34, 1.56, 0.64, 1),
        box-shadow 0.25s cubic-bezier(0.22, 1, 0.36, 1);
    }
    .metro-tile__header--anim:hover {
      transform: translateY(-2px) scale(1.02);
    }
    .metro-tile__header--anim:active {
      transform: scale(0.98);
    }
    .metro-tile__body--anim {
      display: grid;
      grid-template-rows: 0fr;
      opacity: 0;
      transition:
        grid-template-rows 0.32s cubic-bezier(0.22, 1, 0.36, 1),
        opacity 0.32s cubic-bezier(0.22, 1, 0.36, 1);
    }
    .metro-tile__body--anim.is-expanded {
      grid-template-rows: 1fr;
      opacity: 1;
      transition-duration: 0.42s;
    }
    .metro-tile__body-inner {
      min-height: 0;
      overflow: hidden;
    }
    .metro-tile__content--anim {
      opacity: 0;
      transform: translateY(12px);
      transition:
        opacity 0.18s ease,
        transform 0.18s ease;
    }
    .is-expanded .metro-tile__content--anim {
      opacity: 1;
      transform: translateY(0);
      transition:
        opacity 0.32s cubic-bezier(0.22, 1, 0.36, 1) 0.08s,
        transform 0.32s cubic-bezier(0.22, 1, 0.36, 1) 0.08s;
    }
  `,
})
export class MetroTileToggleComponent {
  readonly title = input.required<string>();
  readonly icon = input.required<string>();
  readonly subtitle = input<string | undefined>(undefined);
  readonly color = input<MetroTileColor>('red');
  readonly customColor = input<MetroTileCustomColor | undefined>(undefined);
  readonly size = input<MetroTileSize>('medium');
  readonly badge = input<number | string | null | undefined>(null);
  readonly defaultOpen = input<boolean>(false);
  readonly closeLabel = input<string>('Cerrar');
  readonly className = input<string>('');
  /** Muestra el botón Guardar (equivalente a pasar `onSave`). */
  readonly hasSave = input<boolean>(false);
  readonly saveLabel = input<string>('Guardar');
  readonly saving = input<boolean>(false);
  readonly saveDisabled = input<boolean>(false);

  readonly save = output<void>();

  protected readonly bodyId: string = `metro-tile-body-${++secuencia}`;

  /** Estado lógico (abierto/cerrado). */
  protected readonly open = signal<boolean>(false);
  /** El cuerpo sigue en el DOM durante la animación de cierre. */
  protected readonly rendered = signal<boolean>(false);
  /** Clase que dispara la transición de expansión. */
  protected readonly expanded = signal<boolean>(false);

  private timer: ReturnType<typeof setTimeout> | undefined;
  private inicializado = false;

  protected readonly clases = computed<string>(() => {
    const colorClass: string = this.customColor() ? 'has-custom-color' : `metro-tile--${this.color()}`;
    return [
      'metro-tile',
      colorClass,
      `metro-tile--${this.size()}`,
      this.open() ? 'is-open' : '',
      this.className(),
    ]
      .filter(Boolean)
      .join(' ');
  });

  protected readonly showBadge = computed<boolean>(() => {
    const badge = this.badge();
    return badge !== null && badge !== undefined && badge !== '' && badge !== 0;
  });

  constructor() {
    inject(DestroyRef).onDestroy(() => clearTimeout(this.timer));
    // `defaultOpen` solo se aplica una vez (como el useState inicial del original).
    queueMicrotask(() => {
      if (!this.inicializado && this.defaultOpen()) {
        this.inicializado = true;
        this.abrir(false);
      }
    });
  }

  protected toggle(): void {
    this.inicializado = true;
    if (this.open()) this.cerrar();
    else this.abrir(true);
  }

  private abrir(animar: boolean): void {
    clearTimeout(this.timer);
    this.open.set(true);
    this.rendered.set(true);
    if (animar) {
      requestAnimationFrame(() => requestAnimationFrame(() => this.expanded.set(true)));
    } else {
      this.expanded.set(true);
    }
  }

  protected cerrar(): void {
    clearTimeout(this.timer);
    this.open.set(false);
    this.expanded.set(false);
    this.timer = setTimeout(() => this.rendered.set(false), DURACION_CIERRE_MS);
  }
}
