// FrontEndReact_V1.1/sufiatulado-app/src/shared/ui/components/PageHeader.tsx
import { useNavigate } from 'react-router-dom';

interface Props {
  title: string;
  subtitle?: string;
  icon?: string;
  actions?: React.ReactNode;
  backTo?: string;
}

export function PageHeader({ title, subtitle, icon, actions, backTo }: Props) {
  const navigate = useNavigate();

  return (
    <div className="page-header d-flex align-items-start justify-content-between gap-3 flex-wrap">
      <div className="d-flex align-items-center gap-2">
        {backTo && (
          <button
            className="page-header__back"
            onClick={() => navigate(backTo)}
            aria-label="Volver"
          >
            <i className="bi bi-arrow-left" />
          </button>
        )}
        <div>
          <h2 className="d-flex align-items-center gap-2">
            {icon && <i className={`bi ${icon} text-sufi-red`} style={{ fontSize: '1.5rem' }} />}
            {title}
          </h2>
          {subtitle && <p className="page-subtitle">{subtitle}</p>}
        </div>
      </div>
      {actions && <div className="d-flex gap-2 flex-wrap">{actions}</div>}
    </div>
  );
}

// FrontEndAngular_V1.1/sufiatulado-app/src/shared/ui/components/page-header.component.ts
import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';
import { Router } from '@angular/router';

/**
 * Encabezado de página. Las acciones se proyectan con el atributo `actions`:
 *   <app-page-header title="…"><button actions …>…</button></app-page-header>
 */
@Component({
  selector: 'app-page-header',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="page-header d-flex align-items-start justify-content-between gap-3 flex-wrap">
      <div class="d-flex align-items-center gap-2">
        @if (backTo()) {
          <button class="page-header__back" (click)="volver()" aria-label="Volver">
            <i class="bi bi-arrow-left"></i>
          </button>
        }
        <div>
          <h2 class="d-flex align-items-center gap-2">
            @if (icon()) {
              <i class="bi text-sufi-red" [class]="icon()" style="font-size: 1.5rem"></i>
            }
            {{ title() }}
          </h2>
          @if (subtitle()) {
            <p class="page-subtitle">{{ subtitle() }}</p>
          }
        </div>
      </div>
      <div class="page-header__actions d-flex gap-2 flex-wrap">
        <ng-content select="[actions]" />
      </div>
    </div>
  `,
  styles: `.page-header__actions:empty { display: none !important; }`,
})
export class PageHeaderComponent {
  private readonly router = inject(Router);
  readonly title = input.required<string>();
  readonly subtitle = input<string | undefined>(undefined);
  readonly icon = input<string | undefined>(undefined);
  readonly backTo = input<string | undefined>(undefined);

  protected volver(): void {
    const destino = this.backTo();
    if (destino) void this.router.navigateByUrl(destino);
  }
}
