// FrontEndReact_V1.1/frontend-app/src/shared/ui/components/TomSelectMultiField.tsx
import { useEffect, useRef } from 'react';
import TomSelectLib from 'tom-select';
import 'tom-select/dist/css/tom-select.bootstrap5.css';

export interface TomSelectOption {
  value: string;
  label: string;
}

interface Props {
  id: string;
  options: TomSelectOption[];
  value: string[];
  onChange: (values: string[]) => void;
  placeholder?: string;
  disabled?: boolean;
  required?: boolean;
  maxItems?: number | null;
  maxOptions?: number;
}

export function TomSelectMultiField({
  id,
  options,
  value,
  onChange,
  placeholder = '— Seleccionar —',
  disabled = false,
  required = false,
  maxItems = null,
  maxOptions,
}: Props) {
  const elRef = useRef<HTMLSelectElement>(null);
  const tsRef = useRef<InstanceType<typeof TomSelectLib> | null>(null);
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;

  // Inicializa una sola vez
  useEffect(() => {
    if (!elRef.current) return;
    const ts = new TomSelectLib(elRef.current, {
      plugins: ['remove_button'],
      valueField: 'value',
      labelField: 'label',
      searchField: ['label'],
      placeholder,
      maxItems: maxItems ?? undefined,
      maxOptions: maxOptions ?? options.length,
      options: options.map((option) => ({ value: option.value, label: option.label })),
      items: value,
      onChange(v: unknown) {
        if (Array.isArray(v)) {
          onChangeRef.current(v.map((item) => String(item)));
        } else if (typeof v === 'string' && v !== '') {
          onChangeRef.current([v]);
        } else {
          onChangeRef.current([]);
        }
      },
    });
    tsRef.current = ts;
    return () => {
      ts.destroy();
      tsRef.current = null;
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Sincroniza opciones cuando cambian (sin destruir la instancia)
  useEffect(() => {
    const ts = tsRef.current;
    if (!ts) return;
    ts.clearOptions();
    options.forEach((option) => ts.addOption({ value: option.value, label: option.label }));
    // Re-aplica maxOptions: la lista activa real es la fuente de verdad
    ts.settings.maxOptions = maxOptions ?? options.length;
    ts.refreshOptions(false);
    // Mantener solo los valores que siguen siendo válidos
    const valid: string[] = value.filter((val) => options.some((option) => option.value === val));
    ts.setValue(valid, true);
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [options, maxOptions]);

  // Sincroniza valores desde fuera (carga de edición, reset)
  useEffect(() => {
    const ts = tsRef.current;
    if (!ts) return;
    const raw: unknown = ts.getValue();
    const curArr: string[] = Array.isArray(raw)
      ? raw.map((item) => String(item))
      : raw
        ? [String(raw)]
        : [];
    const sameLength: boolean = curArr.length === value.length;
    const sameItems: boolean = sameLength && curArr.every((item) => value.includes(item));
    if (!sameItems) {
      ts.setValue(value, true);
    }
  }, [value]);

  // Sincroniza estado habilitado/deshabilitado
  useEffect(() => {
    const ts = tsRef.current;
    if (!ts) return;
    if (disabled) ts.disable();
    else ts.enable();
  }, [disabled]);

  return (
    <select
      ref={elRef}
      id={id}
      required={required}
      multiple
      className="form-select"
    />
  );
}

// FrontEndAngular_V1.1/sufiatulado-app/src/shared/ui/components/tom-select-multi-field.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  DestroyRef,
  ElementRef,
  afterNextRender,
  effect,
  inject,
  input,
  model,
  signal,
  untracked,
  viewChild,
} from '@angular/core';
import TomSelect from 'tom-select';
import type { TomSelectOption } from './tom-select-field.component';

function aArreglo(raw: unknown): string[] {
  if (Array.isArray(raw)) return raw.map((item) => String(item));
  return raw ? [String(raw)] : [];
}

/** Select múltiple con búsqueda (Tom Select). Soporta `[(value)]`. */
@Component({
  selector: 'app-tom-select-multi-field',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `<select #el [id]="id()" [required]="required()" multiple class="form-select"></select>`,
})
export class TomSelectMultiFieldComponent {
  readonly id = input.required<string>();
  readonly options = input.required<TomSelectOption[]>();
  readonly value = model<string[]>([]);
  readonly placeholder = input<string>('— Seleccionar —');
  readonly disabled = input<boolean>(false);
  readonly required = input<boolean>(false);
  readonly maxItems = input<number | null>(null);
  readonly maxOptions = input<number | undefined>(undefined);

  private readonly el = viewChild.required<ElementRef<HTMLSelectElement>>('el');
  private readonly ts = signal<TomSelect | null>(null);

  constructor() {
    afterNextRender(() => {
      const options: TomSelectOption[] = untracked(this.options);
      const ts = new TomSelect(this.el().nativeElement, {
        plugins: ['remove_button'],
        valueField: 'value',
        labelField: 'label',
        searchField: ['label'],
        placeholder: untracked(this.placeholder),
        maxItems: untracked(this.maxItems) ?? undefined,
        maxOptions: untracked(this.maxOptions) ?? options.length,
        options: options.map((o) => ({ value: o.value, label: o.label })),
        items: untracked(this.value),
        onChange: (v: unknown) => {
          if (Array.isArray(v)) {
            this.value.set(v.map((item) => String(item)));
          } else if (typeof v === 'string' && v !== '') {
            this.value.set([v]);
          } else {
            this.value.set([]);
          }
        },
      } as never);
      this.ts.set(ts);
    });
    inject(DestroyRef).onDestroy(() => {
      this.ts()?.destroy();
    });

    // Sincroniza opciones cuando cambian (sin destruir la instancia).
    effect(() => {
      const options: TomSelectOption[] = this.options();
      const maxOptions: number | undefined = this.maxOptions();
      const ts = this.ts();
      if (!ts) return;
      untracked(() => {
        ts.clearOptions();
        options.forEach((o) => ts.addOption({ value: o.value, label: o.label }));
        // Re-aplica maxOptions: la lista activa real es la fuente de verdad.
        ts.settings.maxOptions = maxOptions ?? options.length;
        ts.refreshOptions(false);
        // Mantener solo los valores que siguen siendo válidos.
        const valid: string[] = this.value().filter((val) => options.some((o) => o.value === val));
        ts.setValue(valid, true);
      });
    });

    // Sincroniza valores desde fuera (carga de edición, reset).
    effect(() => {
      const value: string[] = this.value();
      const ts = this.ts();
      if (!ts) return;
      const curArr: string[] = aArreglo(ts.getValue());
      const sameItems: boolean =
        curArr.length === value.length && curArr.every((item) => value.includes(item));
      if (!sameItems) {
        ts.setValue(value, true);
      }
    });

    effect(() => {
      const disabled: boolean = this.disabled();
      const ts = this.ts();
      if (!ts) return;
      if (disabled) ts.disable();
      else ts.enable();
    });
  }
}
