// FrontEndAngular_V1.1/sufiatulado-app/src/shared/ui/components/status-badge.component.ts
import { ChangeDetectionStrategy, Component, input } from '@angular/core';

@Component({
  selector: 'app-status-badge',
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <span
      class="badge badge-role"
      [class]="active() ? 'bg-success bg-opacity-15 text-success' : 'bg-secondary bg-opacity-15 text-secondary'"
    >
      <i class="bi bi-circle-fill me-1 status-dot"></i>
      {{ active() ? labels()[0] : labels()[1] }}
    </span>
  `,
})
export class StatusBadgeComponent {
  readonly active = input.required<boolean>();
  readonly labels = input<[string, string]>(['Activo', 'Inactivo']);
}

// FrontEndReact_V1.1/sufiatulado-app/src/shared/ui/components/StatusBadge.tsx
interface Props {
  active: boolean;
  labels?: [string, string];
}

export function StatusBadge({ active, labels = ['Activo', 'Inactivo'] }: Props) {
  return (
    <span
      className={`badge badge-role ${active ? 'bg-success bg-opacity-15 text-success' : 'bg-secondary bg-opacity-15 text-secondary'}`}
    >
      <i className="bi bi-circle-fill me-1 status-dot" />
      {active ? labels[0] : labels[1]}
    </span>
  );
}
