// FrontEndAngular_V1.1/sufiatulado-app/src/pages/admin/departamentos-admin-page.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';
import {
  CatalogoCrudComponent,
  type AvisoBorrado,
  type CampoCatalogo,
  type ColumnaCatalogo,
} from '../../shared/ui/components/catalogo-crud/catalogo-crud.component';
import { injectCatalogoCrud, type FormValues } from '../../shared/ui/components/catalogo-crud/catalogo-crud';
import {
  injectActualizarAdminDepartamento,
  injectAdminDepartamentosList,
  injectCrearAdminDepartamento,
  injectEliminarAdminDepartamento,
} from '../../features/admin-departamentos/model/queries';
import type { AdminDepartamentoFormPayload, AdminDepartamentoListItem } from '../../features/admin-departamentos/model/types';

const COLUMNAS: ColumnaCatalogo<AdminDepartamentoListItem>[] = [
  { header: 'Código', width: 100, tipo: 'code', valor: (i) => i.did },
  { header: 'Nombre', className: 'fw-semibold', tipo: 'text', valor: (i) => i.departamento },
  { header: 'Padre (pid)', width: 120, tipo: 'codeOpcional', valor: (i) => i.pid },
];

const CAMPOS: CampoCatalogo[] = [
  { key: 'departamento', label: 'Nombre', required: true, maxLength: 200, col: 8, placeholder: 'Ej: Antioquia' },
  { key: 'pid', label: 'Padre (pid)', maxLength: 10, col: 4, placeholder: 'Opcional' },
];

const AVISO: AvisoBorrado = { objeto: 'el departamento', nota: 'Si tiene ciudades asociadas, la operación será rechazada.' };

@Component({
  selector: 'app-departamentos-admin-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [CatalogoCrudComponent],
  template: `
    <app-catalogo-crud
      [crud]="crud"
      title="Administrar Departamentos"
      icon="bi-map-fill"
      backTo="/admin/catalogos"
      [columns]="columnas"
      [fields]="campos"
      [deleteWarning]="aviso"
    />
  `,
})
export class DepartamentosAdminPageComponent {
  protected readonly columnas = COLUMNAS;
  protected readonly campos = CAMPOS;
  protected readonly aviso = AVISO;

  private readonly actualizarMut = injectActualizarAdminDepartamento();

  protected readonly crud = injectCatalogoCrud<AdminDepartamentoListItem, AdminDepartamentoFormPayload>({
    singular: 'Departamento',
    idOf: (item) => item.did,
    initForm: { departamento: '', pid: '' },
    itemToForm: (i) => ({ departamento: i.departamento, pid: i.pid !== null ? String(i.pid) : '' }),
    toPayload: (f: FormValues): AdminDepartamentoFormPayload => ({
      departamento: f['departamento'].trim(),
      pid: f['pid'].trim() === '' ? null : Number(f['pid']),
    }),
    validate: (f) => (f['departamento'].trim() ? null : 'El nombre del departamento es obligatorio'),
    list: (q) => injectAdminDepartamentosList(q),
    crear: injectCrearAdminDepartamento(),
    actualizar: (did, payload) => this.actualizarMut.mutateAsync({ did, payload }),
    actualizarPending: this.actualizarMut.isPending,
    eliminar: injectEliminarAdminDepartamento(),
  });
}

// FrontEndReact_V1.1/frontend-app/src/pages/admin/DepartamentosAdminPage.tsx
import { CatalogoCrudPage } from '../../shared/ui/components/CatalogoCrudPage';
import type { FormValues } from '../../shared/ui/components/CatalogoCrudPage';
import {
  useActualizarAdminDepartamento,
  useAdminDepartamentosList,
  useCrearAdminDepartamento,
  useEliminarAdminDepartamento,
} from '../../features/admin-departamentos/model/useAdminDepartamentos';
import type {
  AdminDepartamentoFormPayload,
  AdminDepartamentoListItem,
} from '../../features/admin-departamentos/model/types';

export function DepartamentosAdminPage() {
  const actualizarMut = useActualizarAdminDepartamento();
  return (
    <CatalogoCrudPage<AdminDepartamentoListItem, AdminDepartamentoFormPayload>
      title="Administrar Departamentos"
      icon="bi-map-fill"
      singular="Departamento"
      backTo="/admin/catalogos"
      idOf={(i) => i.did}
      columns={[
        { header: 'Código', width: 100, cell: (i) => <code>{i.did}</code> },
        { header: 'Nombre', className: 'fw-semibold', cell: (i) => i.departamento },
        {
          header: 'Padre (pid)', width: 120,
          cell: (i) => (i.pid !== null ? <code className="small">{i.pid}</code> : <span className="text-muted small">—</span>),
        },
      ]}
      fields={[
        { key: 'departamento', label: 'Nombre', required: true, maxLength: 200, col: 8, placeholder: 'Ej: Antioquia' },
        { key: 'pid', label: 'Padre (pid)', maxLength: 10, col: 4, placeholder: 'Opcional' },
      ]}
      initForm={{ departamento: '', pid: '' }}
      itemToForm={(i) => ({ departamento: i.departamento, pid: i.pid !== null ? String(i.pid) : '' })}
      toPayload={(f: FormValues): AdminDepartamentoFormPayload => ({
        departamento: f.departamento.trim(),
        pid: f.pid.trim() === '' ? null : Number(f.pid),
      })}
      validate={(f) => (f.departamento.trim() ? null : 'El nombre del departamento es obligatorio')}
      deleteWarning={
        <>¿Confirma eliminar el departamento? Esta acción es <strong>permanente</strong>.<br />
          <small className="text-muted">Si tiene ciudades asociadas, la operación será rechazada.</small></>
      }
      useList={useAdminDepartamentosList}
      crearMut={useCrearAdminDepartamento()}
      actualizar={(did, payload) => actualizarMut.mutateAsync({ did, payload })}
      actualizarPending={actualizarMut.isPending}
      eliminarMut={useEliminarAdminDepartamento()}
    />
  );
}
