// FrontEndAngular_V1.1/sufiatulado-app/src/pages/referencias/referencias-page.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { injectQuery } from '@tanstack/angular-query-experimental';
import { ApiClient } from '../../shared/api/client';
import { PageHeaderComponent } from '../../shared/ui/components/page-header.component';
import { LoadingSpinnerComponent } from '../../shared/ui/components/loading-spinner.component';
import { EmptyStateComponent } from '../../shared/ui/components/empty-state.component';
import { QUERY_KEYS } from '../../shared/config/constants';
import type { Canal, Ejecutivo, Oficina } from '../../entities/referencias/model/types';

type Tab = 'canales' | 'oficinas' | 'ejecutivos';

@Component({
  selector: 'app-referencias-page',
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [PageHeaderComponent, LoadingSpinnerComponent, EmptyStateComponent],
  template: `
    <div>
      <app-page-header title="Referencias" subtitle="Catálogos del sistema" icon="bi-diagram-3" />

      <div class="card shadow-sm" style="border: none">
        <div class="card-header bg-white border-0 pt-3">
          <ul class="nav nav-tabs" role="tablist">
            <li class="nav-item">
              <button type="button" class="nav-link" [class.active]="tab() === 'canales'" (click)="tab.set('canales')">
                <i class="bi bi-broadcast me-2"></i>Canales
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="nav-link" [class.active]="tab() === 'oficinas'" (click)="tab.set('oficinas')">
                <i class="bi bi-building me-2"></i>Oficinas
              </button>
            </li>
            <li class="nav-item">
              <button type="button" class="nav-link" [class.active]="tab() === 'ejecutivos'" (click)="tab.set('ejecutivos')">
                <i class="bi bi-person-badge me-2"></i>Ejecutivos
              </button>
            </li>
          </ul>
        </div>
        <div class="card-body p-0">
          @if (isLoading()) {
            <app-loading-spinner [fullPage]="true" />
          } @else {
            @switch (tab()) {
              @case ('canales') {
                @if (canales.data()?.length) {
                  <table class="table table-hover mb-0">
                    <thead><tr><th>ID</th><th>Nombre</th><th>Código</th></tr></thead>
                    <tbody>
                      @for (canal of canales.data(); track canal.id) {
                        <tr><td>{{ canal.id }}</td><td>{{ canal.nombre }}</td><td>{{ canal.codigo ?? '—' }}</td></tr>
                      }
                    </tbody>
                  </table>
                } @else {
                  <app-empty-state icon="bi-broadcast" title="Sin canales" />
                }
              }
              @case ('oficinas') {
                @if (oficinas.data()?.length) {
                  <table class="table table-hover mb-0">
                    <thead><tr><th>ID</th><th>Nombre</th><th>Canal</th></tr></thead>
                    <tbody>
                      @for (oficina of oficinas.data(); track oficina.id) {
                        <tr><td>{{ oficina.id }}</td><td>{{ oficina.nombre }}</td><td>{{ oficina.canal_id ?? '—' }}</td></tr>
                      }
                    </tbody>
                  </table>
                } @else {
                  <app-empty-state icon="bi-building" title="Sin oficinas" />
                }
              }
              @case ('ejecutivos') {
                @if (ejecutivos.data()?.length) {
                  <table class="table table-hover mb-0">
                    <thead><tr><th>Usuario</th><th>Nombre</th><th>Canal</th><th>Oficina</th></tr></thead>
                    <tbody>
                      @for (ejecutivo of ejecutivos.data(); track ejecutivo.id) {
                        <tr>
                          <td class="font-monospace">{{ ejecutivo.usuario_asesor }}</td>
                          <td>{{ ejecutivo.nombre ?? '—' }}</td>
                          <td>{{ ejecutivo.canal ?? '—' }}</td>
                          <td>{{ ejecutivo.oficina ?? '—' }}</td>
                        </tr>
                      }
                    </tbody>
                  </table>
                } @else {
                  <app-empty-state icon="bi-person-badge" title="Sin ejecutivos" />
                }
              }
            }
          }
        </div>
      </div>
    </div>
  `,
})
export class ReferenciasPageComponent {
  private readonly api = inject(ApiClient);
  protected readonly tab = signal<Tab>('canales');

  protected readonly canales = injectQuery<Canal[]>(() => ({
    queryKey: [QUERY_KEYS.REFERENCIAS_CANALES],
    queryFn: async () => (await this.api.get<Canal[]>('/referencias/canales')).data,
    enabled: this.tab() === 'canales',
  }));

  protected readonly oficinas = injectQuery<Oficina[]>(() => ({
    queryKey: [QUERY_KEYS.REFERENCIAS_OFICINAS],
    queryFn: async () => (await this.api.get<Oficina[]>('/referencias/oficinas')).data,
    enabled: this.tab() === 'oficinas',
  }));

  protected readonly ejecutivos = injectQuery<Ejecutivo[]>(() => ({
    queryKey: [QUERY_KEYS.REFERENCIAS_EJECUTIVOS],
    queryFn: async () => (await this.api.get<Ejecutivo[]>('/referencias/ejecutivos')).data,
    enabled: this.tab() === 'ejecutivos',
  }));

  protected readonly isLoading = computed<boolean>(
    () =>
      (this.tab() === 'canales' && this.canales.isLoading()) ||
      (this.tab() === 'oficinas' && this.oficinas.isLoading()) ||
      (this.tab() === 'ejecutivos' && this.ejecutivos.isLoading()),
  );
}

// FrontEndReact_V1.1/frontend-app/src/pages/referencias/ReferenciasPage.tsx
import { useState } from 'react';
import { Nav, Card, Table } from 'react-bootstrap';
import { useQuery } from '@tanstack/react-query';
import { apiClient } from '../../shared/api/client';
import { PageHeader } from '../../shared/ui/components/PageHeader';
import { LoadingSpinner } from '../../shared/ui/components/LoadingSpinner';
import { EmptyState } from '../../shared/ui/components/EmptyState';
import { QUERY_KEYS } from '../../shared/config/constants';
import type { Canal, Oficina, Ejecutivo } from '../../entities/referencias/model/types';

type Tab = 'canales' | 'oficinas' | 'ejecutivos';

export function ReferenciasPage() {
  const [tab, setTab] = useState<Tab>('canales');

  const { data: canales, isLoading: loadingCanales } = useQuery<Canal[]>({
    queryKey: [QUERY_KEYS.REFERENCIAS_CANALES],
    queryFn: async () => { const { data } = await apiClient.get<Canal[]>('/referencias/canales'); return data; },
    enabled: tab === 'canales',
  });

  const { data: oficinas, isLoading: loadingOficinas } = useQuery<Oficina[]>({
    queryKey: [QUERY_KEYS.REFERENCIAS_OFICINAS],
    queryFn: async () => { const { data } = await apiClient.get<Oficina[]>('/referencias/oficinas'); return data; },
    enabled: tab === 'oficinas',
  });

  const { data: ejecutivos, isLoading: loadingEjecutivos } = useQuery<Ejecutivo[]>({
    queryKey: [QUERY_KEYS.REFERENCIAS_EJECUTIVOS],
    queryFn: async () => { const { data } = await apiClient.get<Ejecutivo[]>('/referencias/ejecutivos'); return data; },
    enabled: tab === 'ejecutivos',
  });

  const isLoading = (tab === 'canales' && loadingCanales) || (tab === 'oficinas' && loadingOficinas) || (tab === 'ejecutivos' && loadingEjecutivos);

  return (
    <div>
      <PageHeader title="Referencias" subtitle="Catálogos del sistema" icon="bi-diagram-3" />

      <Card className="shadow-sm" style={{ border: 'none' }}>
        <Card.Header className="bg-white border-0 pt-3">
          <Nav variant="tabs" activeKey={tab} onSelect={(tabKey) => setTab(tabKey as Tab)}>
            <Nav.Item><Nav.Link eventKey="canales"><i className="bi bi-broadcast me-2" />Canales</Nav.Link></Nav.Item>
            <Nav.Item><Nav.Link eventKey="oficinas"><i className="bi bi-building me-2" />Oficinas</Nav.Link></Nav.Item>
            <Nav.Item><Nav.Link eventKey="ejecutivos"><i className="bi bi-person-badge me-2" />Ejecutivos</Nav.Link></Nav.Item>
          </Nav>
        </Card.Header>
        <Card.Body className="p-0">
          {isLoading ? (
            <LoadingSpinner fullPage />
          ) : (
            <>
              {tab === 'canales' && (
                canales?.length ? (
                  <Table hover className="mb-0">
                    <thead><tr><th>ID</th><th>Nombre</th><th>Código</th></tr></thead>
                    <tbody>{canales.map((canal) => <tr key={canal.id}><td>{canal.id}</td><td>{canal.nombre}</td><td>{canal.codigo ?? '—'}</td></tr>)}</tbody>
                  </Table>
                ) : <EmptyState icon="bi-broadcast" title="Sin canales" />
              )}
              {tab === 'oficinas' && (
                oficinas?.length ? (
                  <Table hover className="mb-0">
                    <thead><tr><th>ID</th><th>Nombre</th><th>Canal</th></tr></thead>
                    <tbody>{oficinas.map((oficina) => <tr key={oficina.id}><td>{oficina.id}</td><td>{oficina.nombre}</td><td>{oficina.canal_id ?? '—'}</td></tr>)}</tbody>
                  </Table>
                ) : <EmptyState icon="bi-building" title="Sin oficinas" />
              )}
              {tab === 'ejecutivos' && (
                ejecutivos?.length ? (
                  <Table hover className="mb-0">
                    <thead><tr><th>Usuario</th><th>Nombre</th><th>Canal</th><th>Oficina</th></tr></thead>
                    <tbody>{ejecutivos.map((ejecutivo) => <tr key={ejecutivo.id}><td className="font-monospace">{ejecutivo.usuario_asesor}</td><td>{ejecutivo.nombre ?? '—'}</td><td>{ejecutivo.canal ?? '—'}</td><td>{ejecutivo.oficina ?? '—'}</td></tr>)}</tbody>
                  </Table>
                ) : <EmptyState icon="bi-person-badge" title="Sin ejecutivos" />
              )}
            </>
          )}
        </Card.Body>
      </Card>
    </div>
  );
}
